import { type MockPost, type MockComment } from "./types";

export const CATEGORIES = [
  { key: "all", label: "All", icon: "🏠" },
  { key: "academics", label: "Academics", icon: "📚" },
  { key: "exchange", label: "Exchange", icon: "🌍" },
  { key: "internships", label: "Internships", icon: "💼" },
  { key: "campus", label: "Campus Life", icon: "🎓" },
  { key: "papers", label: "Exam Papers", icon: "📄" },
] as const;

export const FLAIRS: Record<string, string[]> = {
  academics: ["Course Review", "Professor Insight", "Study Tips", "Elective Advice", "Core Course", "Question"],
  exchange: ["Experience Diary", "Application Tips", "Living Abroad", "Academics Abroad", "Question"],
  internships: ["Company Review", "Interview Prep", "Stipend Info", "PPO Experience", "Question"],
  campus: ["Food & Cafes", "Study Spots", "Weekend Getaways", "Gyms & Sports", "Transport", "Pro Tip"],
  papers: ["End Term", "Mid Term", "Quiz", "Case Analysis", "Study Material"],
};

export const MOCK_POSTS: MockPost[] = [
  {
    id: "mock-1",
    user_id: "mock-user-1",
    category: "academics",
    title: "Honest review of Corporate Finance with Prof. Srinivasan — worth the grind",
    body: "Just finished CF this term and wanted to share my experience. The course is intense but genuinely one of the best at IIMB.\n\n**Workload**: Heavy. Expect 3-4 case preps per week, plus the group project. Start early.\n\n**Teaching style**: Prof. Srinivasan uses cold calls extensively. Come prepared or face embarrassment. That said, he's incredibly knowledgeable and his real-world examples from his consulting days are gold.\n\n**Grading**: Fair but tough. The bell curve is real. Mid-term was straightforward if you understood DCF models. End-term had a curveball with the LBO question.\n\n**Tips**: \n- Form your study group early\n- Berk DeMarzo is your bible\n- Attend every class — participation is 15%\n- Office hours are underrated, go ask questions\n\nOverall: 4.5/5. Hard but you'll come out actually understanding corporate finance, not just passing an exam.",
    flair: "Course Review",
    upvote_count: 47,
    downvote_count: 3,
    comment_count: 12,
    pinned: false,
    course_code: "FIN301",
    course_name: "Corporate Finance",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    author_name: "Arjun M.",
    author_batch: "PGP 2025",
  },
  {
    id: "mock-2",
    user_id: "mock-user-2",
    category: "internships",
    title: "McKinsey Summer Internship — What they don't tell you in PPTs",
    body: "Did my summers at McK Gurgaon. Here's the unfiltered version:\n\n**The good:**\n- Steep learning curve. First week felt like drinking from a firehose, but by week 3 you're actually contributing to client meetings.\n- Mentorship is real. My EM spent 30 mins daily just coaching me.\n- Stipend: ₹3.5L/month + housing + travel. Can't complain.\n\n**The reality check:**\n- Work hours are brutal. 9am to midnight was my average. Weekend work happened twice.\n- Not every project is sexy strategy. I spent 2 weeks on a cost optimization project that was mostly Excel.\n- The culture is competitive. Other interns are all gunning for the PPO.\n\n**PPO tips:**\n- Deliver above expectations on your main project\n- Network with partners during social events\n- Ask for feedback proactively — don't wait for reviews\n\nGot my PPO. Happy to answer questions in comments.",
    flair: "Company Review",
    upvote_count: 89,
    downvote_count: 5,
    comment_count: 34,
    pinned: false,
    company_name: "McKinsey & Company",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    author_name: "Priya S.",
    author_batch: "PGP 2024",
  },
  {
    id: "mock-3",
    user_id: "mock-user-3",
    category: "exchange",
    title: "HEC Paris exchange — A semester that changed my perspective",
    body: "Spent Term 5 at HEC Paris. Here's everything you need to know:\n\n**Academics**: Courses are more discussion-based than IIMB. Luxury Brand Management and European Business Environment were standout courses. Grading is lenient compared to IIMB.\n\n**Living**: Campus is in Jouy-en-Josas, 30 mins from Paris by RER. Dorm rooms are decent. Budget ≈ €1200/month (with cooking). Eating out in Paris gets expensive fast.\n\n**Social life**: The international cohort is amazing — 80+ nationalities. Thursday parties at the student bar are legendary. Weekend trips to other European cities are easy and cheap with FlixBus/Ryanair.\n\n**Travel**: Did Barcelona, Amsterdam, Rome, and London over weekends. Pro tip: Book 2 months in advance.\n\n**Application tips**: Apply early, maintain 3.0+ GPA, and write a genuine SOP about what you want from the exchange.\n\nWould I do it again? In a heartbeat. 🇫🇷",
    flair: "Experience Diary",
    upvote_count: 63,
    downvote_count: 2,
    comment_count: 21,
    pinned: false,
    college_name: "HEC Paris",
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    author_name: "Kavya R.",
    author_batch: "PGP 2024",
  },
  {
    id: "mock-4",
    user_id: "mock-user-4",
    category: "campus",
    title: "Ultimate food guide for new PGP students — save this post",
    body: "After 2 years at IIMB, here's the definitive food ranking:\n\n**On Campus:**\n1. 🥇 Prakruthi — Best coffee and sandwiches. The cold brew is addictive.\n2. 🥈 MDC Mess — Hit or miss but Thursday paneer is elite\n3. 🥉 CCD — For when you need sugar and caffeine at 2am\n\n**Near Campus (Bannerghatta Road):**\n1. Vidyarthi Bhavan (weekends only, go early) — Masala dosa that changes lives\n2. Meghana Foods — Biryani for ₹250. Andhra meals are fire too.\n3. Third Wave Coffee — Best workspace outside campus\n\n**Delivery essentials:**\n- Swiggy One is worth it if you order 3+ times a week\n- Zomato Pro Plus gets you priority delivery during late-night cram sessions\n\n**Pro tips:**\n- Keep instant noodles for post-midnight study sessions\n- The fruits vendor near the back gate has the best prices\n- Friday night is pizza night at Domino's — they know IIMB students by name at this point 😂",
    flair: "Food & Cafes",
    upvote_count: 112,
    downvote_count: 4,
    comment_count: 45,
    pinned: true,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    author_name: "Rohan K.",
    author_batch: "PGP 2025",
  },
  {
    id: "mock-5",
    user_id: "mock-user-5",
    category: "academics",
    title: "Which marketing electives are actually useful? Need advice for Term 4",
    body: "Hey everyone, I'm a Term 3 student trying to decide on marketing electives for next term. I'm interested in brand management roles post-MBA.\n\nOptions I'm considering:\n1. **Consumer Behaviour** (Prof. Sharma) — heard it's theory-heavy but foundational\n2. **Digital Marketing Analytics** (Prof. Patel) — more hands-on with tools\n3. **Brand Management** (Prof. Rao) — directly relevant but heard grading is tough\n\nAnyone who's taken these — what would you recommend? Especially interested in which ones actually helped in placements or gave practical skills.\n\nAlso open to suggestions I haven't considered. Thanks! 🙏",
    flair: "Question",
    upvote_count: 28,
    downvote_count: 1,
    comment_count: 18,
    pinned: false,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    author_name: "Sneha T.",
    author_batch: "PGP 2026",
  },
  {
    id: "mock-6",
    user_id: "mock-user-6",
    category: "papers",
    title: "Microeconomics End Term 2024 — with solutions and analysis",
    body: "Sharing the Microeconomics end term paper from Term 1 (2024 batch).\n\n**Paper structure:**\n- Section A: 20 MCQs (40 marks) — mostly from Varian chapters 1-15\n- Section B: 3 long-answer questions (60 marks) — game theory, market structures, consumer choice\n\n**Difficulty**: Moderate. If you've done the problem sets, Section A is straightforward. Section B Q2 (Cournot vs Bertrand comparison) was the hardest.\n\n**Key topics that came up:**\n- Price discrimination (3rd degree)\n- Nash equilibrium in mixed strategies\n- Slutsky decomposition\n- Welfare analysis of monopoly vs perfect competition\n\n**Study advice**: Focus on problem sets and tutorial sheets. Past papers from 2022 and 2023 had similar patterns.\n\nI've attached my solutions — not official but I scored 85+ so they should be reliable. Happy to discuss any specific questions.",
    flair: "End Term",
    upvote_count: 76,
    downvote_count: 1,
    comment_count: 23,
    pinned: false,
    course_code: "ECON201",
    course_name: "Microeconomics",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    author_name: "Aditya P.",
    author_batch: "PGP 2025",
  },
  {
    id: "mock-7",
    user_id: "mock-user-7",
    category: "internships",
    title: "Bain vs BCG — did both interviews, got one offer. Here's my comparison",
    body: "Got shortlisted for both Bain and BCG during summers placement. Here's my experience:\n\n**Bain interview process:**\n- 3 rounds: 2 case + 1 fit\n- Cases were structured, market-sizing heavy\n- Fit round was conversational, they really care about 'Bain culture'\n- Timeline: Very fast, got result same day\n\n**BCG interview process:**\n- 4 rounds: 3 case + 1 fit\n- Cases were more creative/unstructured\n- They test mental math aggressively\n- One round had a written case (30 mins)\n\n**My prep that worked:**\n- Case in Point (book) for frameworks\n- 50+ mock cases with friends\n- Victor Cheng videos on YouTube\n- Practiced mental math 30 mins daily for 2 weeks\n\nEnded up at Bain. The culture fit was stronger for me personally. Both are amazing firms though — you can't go wrong with either.\n\nHappy to do mock cases with juniors. DM me.",
    flair: "Interview Prep",
    upvote_count: 94,
    downvote_count: 3,
    comment_count: 41,
    pinned: false,
    company_name: "Bain & Company",
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    author_name: "Vikram D.",
    author_batch: "PGP 2024",
  },
  {
    id: "mock-8",
    user_id: "mock-user-8",
    category: "campus",
    title: "Best study spots ranked — from a night owl who's tried them all",
    body: "After pulling 100+ late nights over 2 years, here's my definitive ranking:\n\n**S-Tier:**\n- Library 2nd floor corner seats — quiet, good AC, power outlets. Get there by 9pm or forget it.\n- MDC reading room — underrated, always has space past 11pm\n\n**A-Tier:**\n- Classroom blocks after 9pm — empty classrooms with whiteboards are perfect for group study\n- Prakruthi outdoor seating — great for morning study sessions (7-9am)\n\n**B-Tier:**\n- Hostel common rooms — depends on your block. D-block is quietest\n- OAT area benches — nice vibes but mosquitoes after sunset\n\n**Avoid:**\n- Library ground floor — too social, you'll end up chatting\n- CCD — expensive, noisy, and they give you looks if you sit too long\n\n**Pro tips:**\n- Invest in noise-cancelling headphones. Life-changing.\n- Keep a blanket in your bag for the over-AC'd library\n- The secret is consistency — find YOUR spot and own it",
    flair: "Study Spots",
    upvote_count: 68,
    downvote_count: 2,
    comment_count: 29,
    pinned: false,
    created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    author_name: "Meera J.",
    author_batch: "PGP 2025",
  },
  {
    id: "mock-9",
    user_id: "mock-user-9",
    category: "exchange",
    title: "NUS Singapore — the practical guide nobody gives you",
    body: "Just returned from NUS. Cutting through the fluff — here's what actually matters:\n\n**Housing**: Apply for UTown residences ASAP. They fill up fast. Monthly rent ~SGD 600-800. Off-campus is cheaper but commute kills you.\n\n**Courses to take:**\n- Venture Capital & Private Equity — Prof. Wong is brilliant\n- Asian Business Context — easy A and genuinely interesting\n- Avoid: Quantitative Finance unless you love pain\n\n**Budget reality check:**\n- Monthly spend: SGD 2000-2500 (being careful)\n- Hawker centers = survival. ₹200-300 per meal equivalent\n- Grab (Uber equivalent) is expensive. MRT everywhere.\n\n**Weekend trips:**\n- Malaysia (Johor Bahru): 1hr bus, cheap shopping\n- Bali: ₹5k flights if booked early\n- Bangkok: Budget airlines make this feasible\n\n**What I wish I knew:**\n- Open a DBS bank account immediately — PayNow makes life easy\n- Get the student EZ-Link card for transport\n- Join at least 2 NUS clubs — that's where you meet people\n\nOverall: 4/5. Not as glamorous as Europe but incredibly practical if you want Asia-focused career.",
    flair: "Experience Diary",
    upvote_count: 51,
    downvote_count: 2,
    comment_count: 16,
    pinned: false,
    college_name: "NUS Singapore",
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    author_name: "Rahul N.",
    author_batch: "PGP 2025",
  },
  {
    id: "mock-10",
    user_id: "mock-user-10",
    category: "academics",
    title: "Data Science elective is being completely revamped — here's what I heard",
    body: "Spoke to Prof. Kumar's RA today. Apparently the Data Science & AI elective for next term is getting a major overhaul:\n\n**New additions:**\n- Hands-on projects with real company datasets (not just Kaggle)\n- GenAI module covering LLMs, prompt engineering, and business applications\n- Guest lectures from IIMB alumni at Google and Microsoft\n\n**What's staying:**\n- Python/R programming foundation\n- Statistical modeling and regression\n- Group project (but now with industry mentors)\n\n**What's gone:**\n- The painful SAS component (finally!)\n- The 50-page report — replaced with a pitch deck + demo\n\nIf this is true, it could become the most popular elective. For those targeting analytics/PM roles, this might be a no-brainer.\n\nAnyone else heard similar things? Would love confirmation before I commit my bidding points.",
    flair: "Elective Advice",
    upvote_count: 35,
    downvote_count: 4,
    comment_count: 22,
    pinned: false,
    course_code: "BA401",
    course_name: "Data Science & AI",
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    author_name: "Ananya S.",
    author_batch: "PGP 2026",
  },
];

export const MOCK_COMMENTS: Record<string, MockComment[]> = {
  "mock-1": [
    {
      id: "c1",
      post_id: "mock-1",
      parent_id: null,
      user_id: "mock-user-5",
      body: "Totally agree on the office hours point. Prof. Srinivasan is a different person one-on-one — much more approachable and he actually gives hints about what to focus on for exams.",
      upvote_count: 15,
      downvote_count: 0,
      created_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
      author_name: "Sneha T.",
      author_batch: "PGP 2026",
      replies: [
        {
          id: "c1-1",
          post_id: "mock-1",
          parent_id: "c1",
          user_id: "mock-user-3",
          body: "Can confirm. Went to office hours twice before end-term and my grade jumped significantly. He basically told me which chapters to prioritize.",
          upvote_count: 8,
          downvote_count: 0,
          created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
          author_name: "Kavya R.",
          author_batch: "PGP 2024",
          replies: [],
        },
      ],
    },
    {
      id: "c2",
      post_id: "mock-1",
      parent_id: null,
      user_id: "mock-user-8",
      body: "Was the LBO question similar to the practice problems or completely out of left field? I'm taking this next term and want to be prepared.",
      upvote_count: 6,
      downvote_count: 0,
      created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      author_name: "Meera J.",
      author_batch: "PGP 2025",
      replies: [
        {
          id: "c2-1",
          post_id: "mock-1",
          parent_id: "c2",
          user_id: "mock-user-1",
          body: "It was a twist on the textbook format. Instead of giving you the debt schedule, you had to build it from scratch given some constraints. Practice building LBO models from scratch and you'll be fine.",
          upvote_count: 11,
          downvote_count: 0,
          created_at: new Date(Date.now() - 0.5 * 60 * 60 * 1000).toISOString(),
          author_name: "Arjun M.",
          author_batch: "PGP 2025",
          replies: [],
        },
      ],
    },
    {
      id: "c3",
      post_id: "mock-1",
      parent_id: null,
      user_id: "mock-user-4",
      body: "What study group size do you recommend? We had 6 people last term and it felt too big — hard to coordinate schedules.",
      upvote_count: 4,
      downvote_count: 0,
      created_at: new Date(Date.now() - 0.8 * 60 * 60 * 1000).toISOString(),
      author_name: "Rohan K.",
      author_batch: "PGP 2025",
      replies: [],
    },
  ],
  "mock-2": [
    {
      id: "c4",
      post_id: "mock-2",
      parent_id: null,
      user_id: "mock-user-7",
      body: "Thanks for the honest take. How did you handle the work-life balance? I've heard some interns burn out by week 4.",
      upvote_count: 12,
      downvote_count: 0,
      created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      author_name: "Vikram D.",
      author_batch: "PGP 2024",
      replies: [
        {
          id: "c4-1",
          post_id: "mock-2",
          parent_id: "c4",
          user_id: "mock-user-2",
          body: "Honestly, the first 2 weeks are survival mode. After that you find a rhythm. I made it a point to gym every morning at 7am regardless — that was my non-negotiable. Also, your EM usually buffers you from partner pressure, so build that relationship early.",
          upvote_count: 18,
          downvote_count: 0,
          created_at: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
          author_name: "Priya S.",
          author_batch: "PGP 2024",
          replies: [],
        },
      ],
    },
  ],
};

export function timeAgo(dateString: string): string {
  const now = new Date();
  const date = new Date(dateString);
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);

  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  const months = Math.floor(days / 30);
  return `${months}mo ago`;
}
